# Generated by Django 3.2.3 on 2021-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='titlePgImg',
            field=models.ImageField(upload_to='BookStore/', verbose_name='Title Page Image'),
        ),
    ]
