# Generated by Django 3.2.3 on 2021-08-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_titlepgimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.FileField(upload_to='BookPDF/', verbose_name='Location'),
        ),
    ]
